[[libgeotiff]]
arch = "aarch64"
git-tree-sha1 = "64ec256fcc475a028712bfeaa134da7ffcaebd64"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "42bc05d931d6390459630bf9b95c68bac39b94f657be4d4742752e34c3f763f3"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+0/libgeotiff.v1.6.0.aarch64-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "aarch64"
git-tree-sha1 = "74710e4a014d43a638ce0277f4234cdb16f538e8"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "9af592b7fd9b0a1e7df3dae945f72a1cf6253ee30cc63a53b990d3ee5396931a"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+0/libgeotiff.v1.6.0.aarch64-linux-musl.tar.gz"
[[libgeotiff]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7e654e8cadf4f95e45c4ceb932eb10c14c9f8975"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "7a912b25f924b10b2c35111ffc9038fc05d2fe8b10b07b343516afd8ba5cc901"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+0/libgeotiff.v1.6.0.armv7l-linux-gnueabihf.tar.gz"
[[libgeotiff]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "55ce0822b488b2d85238d326adb716f300d3e4c3"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "9534b96ae86b4a2b9f2e92b2a6e24ffe0fdc83538f3164001f345f4deabe78b3"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+0/libgeotiff.v1.6.0.armv7l-linux-musleabihf.tar.gz"
[[libgeotiff]]
arch = "i686"
git-tree-sha1 = "a6ae0a659bd3d4ed87f4a8dc8d952d1865b321c8"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "de8e0334516bb55f32a6866eb2891cf8304c49de0c8fc21e2a577ceee35b524d"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+0/libgeotiff.v1.6.0.i686-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "i686"
git-tree-sha1 = "5c9fdd5d9025936d0c0e3b5c42f7f34921725c1b"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "1addc7ec76d4ca5f12be75628ad3555c62740f1895cf4dfc96dcf8200637972e"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+0/libgeotiff.v1.6.0.i686-linux-musl.tar.gz"
[[libgeotiff]]
arch = "i686"
git-tree-sha1 = "bc517ba1aeaebadf669a142bba565f0fde49fb67"
os = "windows"

    [[libgeotiff.download]]
    sha256 = "c0e2e9cc6724db891e775fed9d5b71fb8189e7d3b116a01b0242b433cfb43685"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+0/libgeotiff.v1.6.0.i686-w64-mingw32.tar.gz"
[[libgeotiff]]
arch = "powerpc64le"
git-tree-sha1 = "18ab0eb7e211cf13aa7a895494e7b48b4096855d"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "c5ad48356d089b6665482d12a6e0039623c50168d4d8dd78583de0105e8f09eb"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+0/libgeotiff.v1.6.0.powerpc64le-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "33ad4199f4e0f220990d17d51897ef0bc397b50b"
os = "macos"

    [[libgeotiff.download]]
    sha256 = "7e5af8b432ed212ae973bde37e686e6f3a912e003128f0a5e24bdbe35e04f8a6"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+0/libgeotiff.v1.6.0.x86_64-apple-darwin.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "082e6b7037c09fc29f9b54bbf952b9f0542de706"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "20afdd3ad568e505f75a6dcb0e35aa4bf552fb297baaa2b636ef7b889eeb9c1b"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+0/libgeotiff.v1.6.0.x86_64-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "ecc5853339e08b3350843c9b76a832335e0d39c0"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "84674d689acb735e30198d3c21fce8f5e332dff73faa43b54d7afe598f0fb847"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+0/libgeotiff.v1.6.0.x86_64-linux-musl.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "21b21c94930859b0dc45cc57e6be4f6841b70207"
os = "freebsd"

    [[libgeotiff.download]]
    sha256 = "6c884cda49a0ffc0e56de6a7c1c877704932422ee7026de6840c11ce57ea7af2"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+0/libgeotiff.v1.6.0.x86_64-unknown-freebsd.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "c245c492985da9bb247d02475a7be543f3d604ee"
os = "windows"

    [[libgeotiff.download]]
    sha256 = "e3144c66fc3eb518df9aae826ad76b5782a420e29c44dbd52fe9b7e74fceffc5"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+0/libgeotiff.v1.6.0.x86_64-w64-mingw32.tar.gz"
