[[libgeotiff]]
arch = "aarch64"
git-tree-sha1 = "b8e8564cc9293348d6cae47db94135cf49f14795"
os = "macos"

    [[libgeotiff.download]]
    sha256 = "8c8c1ac6c60acd1c18c425bd261258ed35296a6a8037049b6dd7dfe514789604"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.101+0/libgeotiff.v100.700.101.aarch64-apple-darwin.tar.gz"
[[libgeotiff]]
arch = "aarch64"
git-tree-sha1 = "85bd2ce419c4bc0ffd7ff22a82216b6c07c70007"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "f0052cf7635c4967a153450ffb42dc056e948d643195ef41ba1290bb3f541e71"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.101+0/libgeotiff.v100.700.101.aarch64-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "aarch64"
git-tree-sha1 = "fa43eef974391b702db7f2e78c510169a412d40e"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "0c39a50464bde59b2b6d8e111ff6684306034da8a6bc40e2d16b676293737fb0"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.101+0/libgeotiff.v100.700.101.aarch64-linux-musl.tar.gz"
[[libgeotiff]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "78d51cd7c0afb5a1f168149fb0f777d4b663bce9"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "fc8f9fa6c919b1561600b0d838801637965180f0d316a5e7a3037f47f492468d"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.101+0/libgeotiff.v100.700.101.armv6l-linux-gnueabihf.tar.gz"
[[libgeotiff]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "df60d7818488688ef6be22b01d87d0da4e27de1c"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "1d2565e83007329119a7b2663f67d5a4c62c6b0a5e8e2aaeb4f0592e7ac086e0"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.101+0/libgeotiff.v100.700.101.armv6l-linux-musleabihf.tar.gz"
[[libgeotiff]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "aa2e78bb6225da04cf3c425f20dacd96bb35d2ce"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "dd1f346e538427cf4be6b5cc3f6d290a38b29b5737ec2014be0f98437ea81e23"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.101+0/libgeotiff.v100.700.101.armv7l-linux-gnueabihf.tar.gz"
[[libgeotiff]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eca911e5136195d80cda7132fe7b3320d212d002"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "54b5baec6c0fea5419cbf8fefee607bda9b393d751f46f115ada80583945ffc0"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.101+0/libgeotiff.v100.700.101.armv7l-linux-musleabihf.tar.gz"
[[libgeotiff]]
arch = "i686"
git-tree-sha1 = "c6d9d4d8576813f85a28557acc57772706d1d163"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "d5442b37139df48ea2e0d316a79f370a6a921f0f21c9b3cc7f67f6f4a1d8bda6"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.101+0/libgeotiff.v100.700.101.i686-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "i686"
git-tree-sha1 = "a350132959805a6e57cafe44bf3859d703fb6edb"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "a4ccbd9ac51bab98589025237930834ce4e9dee4818dafb9762014ebb435e180"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.101+0/libgeotiff.v100.700.101.i686-linux-musl.tar.gz"
[[libgeotiff]]
arch = "i686"
git-tree-sha1 = "6d8435a27701e3d1c9d90e9ae23d035005318502"
os = "windows"

    [[libgeotiff.download]]
    sha256 = "3ae08933ca34724da796dcec6c495a3e01dc9b95715c2e68d75b5336391f328f"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.101+0/libgeotiff.v100.700.101.i686-w64-mingw32.tar.gz"
[[libgeotiff]]
arch = "powerpc64le"
git-tree-sha1 = "291dc21aefb07f0264e1f07d1e2191338c53275c"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "8556c3aacce2b8d5b33b2f8d3395ef7aa53f57440bda39a8daeb4241bd18e9e5"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.101+0/libgeotiff.v100.700.101.powerpc64le-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "ce847174692f907927c476f8d71cfb30e3b18add"
os = "macos"

    [[libgeotiff.download]]
    sha256 = "69eaeccd13cc097df256afff6dedd16bdbccfe8d6e7abe3b2b8d2f6500c692b0"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.101+0/libgeotiff.v100.700.101.x86_64-apple-darwin.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "0fb63fd1bc087e100b8ed561afc27bb6fd724227"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "e216de423b5bb177e0dab1f1a99ca50b1f3fb34c0c5feacb8b53b82d2cff5763"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.101+0/libgeotiff.v100.700.101.x86_64-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "1635de7c7aa6ee5dc45d88e1908f3b2059f42e08"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "a10f4cb0bc3a9a1486729d861253c67c949ca0010ad9f30c86392e2a754faf95"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.101+0/libgeotiff.v100.700.101.x86_64-linux-musl.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "3096ebbdf668c3c01e60c14acd177261873cedd8"
os = "freebsd"

    [[libgeotiff.download]]
    sha256 = "ff7c5e5d2acc8ab99ea196b9d6d4b9bb20d7cd1106c248f1ffa3bf7f93bd5644"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.101+0/libgeotiff.v100.700.101.x86_64-unknown-freebsd.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "084ce18d5172ed31b99675999330e0eeea185259"
os = "windows"

    [[libgeotiff.download]]
    sha256 = "905b954234d9214f82d194313636535022de38eb017e42ba3dd2514171a8f435"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.101+0/libgeotiff.v100.700.101.x86_64-w64-mingw32.tar.gz"
