[[libgeotiff]]
arch = "aarch64"
git-tree-sha1 = "e0af759eafec1f8ea0bb6d8bb2e1e5e53a6d8dfa"
os = "macos"

    [[libgeotiff.download]]
    sha256 = "92b3f719d822f4bff3ac9bc29e6ef3b8147c10e000c231987ab7d1a1156ee469"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.7.1+0/libgeotiff.v1.7.1.aarch64-apple-darwin.tar.gz"
[[libgeotiff]]
arch = "aarch64"
git-tree-sha1 = "a64a09050dc027f3458e599f31adbafb64628103"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "6ccbf66be933d0a012cc5564bd9f74ea1ef1ce062d5cd5032b08bf8798ab5b05"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.7.1+0/libgeotiff.v1.7.1.aarch64-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "aarch64"
git-tree-sha1 = "93d2964bca69a62f2bda835c80c58044a127078d"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "8e342202c571a22c184ee437fbf05c661e8eed11a325e0d00e7e0e871a32519a"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.7.1+0/libgeotiff.v1.7.1.aarch64-linux-musl.tar.gz"
[[libgeotiff]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "97578acc8ad6ade5d60773deba9916d440b5c0cf"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "8b204fa9edd567dcc259d98ecbb924d64c2c708299de42016e3ae8b3a22cb64f"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.7.1+0/libgeotiff.v1.7.1.armv6l-linux-gnueabihf.tar.gz"
[[libgeotiff]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3ffba7e6455ddb059c45e65d2ecbb43e2c2e26ca"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "a7a02f1063d79bed4c56125ebc020bf1aaaa3bc6276126742a97055d8f9831bd"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.7.1+0/libgeotiff.v1.7.1.armv6l-linux-musleabihf.tar.gz"
[[libgeotiff]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "40e6f0119142eb67aaa054b5be16767dc7a20f5c"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "9d1725162101e763db91794289d08fea004b941af1cd87c1cb17bce5f9b2ed00"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.7.1+0/libgeotiff.v1.7.1.armv7l-linux-gnueabihf.tar.gz"
[[libgeotiff]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a31b4413427e1bb6ea2eb84db83f075a2b483548"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "3c3ad0f8163ff03c58377ef7b2140fd5c36eeb566e7a9abd017a86b1637885ac"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.7.1+0/libgeotiff.v1.7.1.armv7l-linux-musleabihf.tar.gz"
[[libgeotiff]]
arch = "i686"
git-tree-sha1 = "112a3cae3f24f0fd82e6b56c8ce47cb3b1af610f"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "5ab0745493518793d519a26e3432c6db0c2142790064a682b2cfd83daa3ff034"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.7.1+0/libgeotiff.v1.7.1.i686-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "i686"
git-tree-sha1 = "edcbbfa6615cca2d7abd3ae38a42d4abdec3dc30"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "0a4925b7490ced934727104d498147d01f3f98f3f5f63becc1a02a250110a92d"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.7.1+0/libgeotiff.v1.7.1.i686-linux-musl.tar.gz"
[[libgeotiff]]
arch = "i686"
git-tree-sha1 = "5504a7672227c77f0207c962afd48a06e9e86fa0"
os = "windows"

    [[libgeotiff.download]]
    sha256 = "15e1d7bf01f98800a09ccbf4352a112050d5e1ae06146c0c020b30a5582e6c83"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.7.1+0/libgeotiff.v1.7.1.i686-w64-mingw32.tar.gz"
[[libgeotiff]]
arch = "powerpc64le"
git-tree-sha1 = "ddb7333b3929f635490c26e67fbcf097ec3bb521"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "5ec8e839d25c9cbd194cea8cf4018a81095b702886c7aeff15881ab37ffaa426"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.7.1+0/libgeotiff.v1.7.1.powerpc64le-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "b830cc17c4d8132b1a1bad9e37b9243824e156f4"
os = "macos"

    [[libgeotiff.download]]
    sha256 = "e70c8d8ffad701a1bf0362a4d9fe8ba192ffffd03dfc579ff6cad0e4758a8ec2"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.7.1+0/libgeotiff.v1.7.1.x86_64-apple-darwin.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "8fb40c2d8564b51f93081fb29909958389b8799e"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "f964bebabedafb395f4232e2653ada41a463bf426e9fcf1d47f463f5387bf68d"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.7.1+0/libgeotiff.v1.7.1.x86_64-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "f7c9932b88381a34001475a44d1d291c445cd879"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "cf7e73b77db2d845d918a21afdf496f1a881d0b6649921c4f852980fab7f2ae4"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.7.1+0/libgeotiff.v1.7.1.x86_64-linux-musl.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "c2154cf9866803382b7b5900e06c40fbb0b4b4fd"
os = "freebsd"

    [[libgeotiff.download]]
    sha256 = "f0bdd7412c22e63fe038703bd27b7bbae0c04d6bc6ae60cab183ae7df55b4282"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.7.1+0/libgeotiff.v1.7.1.x86_64-unknown-freebsd.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "f1f02194dc1d6a14c934c9014106ca8440640c34"
os = "windows"

    [[libgeotiff.download]]
    sha256 = "ea991413d3e07b492ffda384849c8c97e3cb9e932d7b40441bb906519711ed1d"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.7.1+0/libgeotiff.v1.7.1.x86_64-w64-mingw32.tar.gz"
