[[libgeotiff]]
arch = "aarch64"
git-tree-sha1 = "cb7a6876ca840c103502fc7229d923953114e766"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "7004a2792d7aaef8bda57a4b5eae872b4ee67f26f48c6aff3c001b4509f33c9c"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+1/libgeotiff.v1.6.0.aarch64-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "aarch64"
git-tree-sha1 = "f87b0b5faa8199b85fa5c09d111c7e5a85307921"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "20a347d771aed400041307642f92e0d45cc0a4680a8f81fec0df63de28c8cfc8"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+1/libgeotiff.v1.6.0.aarch64-linux-musl.tar.gz"
[[libgeotiff]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "875756ae29e41170fec6bf1a9455efe99d2769f4"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "79e937756ebf2e362250182a30f6c3286c0f45e1b15aa1d33b3fdbd2eadbc7f3"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+1/libgeotiff.v1.6.0.armv7l-linux-gnueabihf.tar.gz"
[[libgeotiff]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5ba7bb3c013c54e791196e5c2bbcf352b4dec9c6"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "0912c0ab4e48b5424448b556469f74b547b366c93381562d288300c4e2805769"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+1/libgeotiff.v1.6.0.armv7l-linux-musleabihf.tar.gz"
[[libgeotiff]]
arch = "i686"
git-tree-sha1 = "a8fcd95c26e3ac3ea6e81a3ee8ff5ac96a8e96f7"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "f13820f333cbb3e7ecb110806de82251f6dcabfe9974c9d1d683fdd63ae78409"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+1/libgeotiff.v1.6.0.i686-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "i686"
git-tree-sha1 = "e71de5f707feaf669b19fb1aeb7afad28c9268ba"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "086a13c49bffba7a75c7b344ab6536c3dd063d263c1e89da935e4dd0e6e254d2"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+1/libgeotiff.v1.6.0.i686-linux-musl.tar.gz"
[[libgeotiff]]
arch = "i686"
git-tree-sha1 = "0d644b657b8557ab66cb6f9e0ee90098a3585935"
os = "windows"

    [[libgeotiff.download]]
    sha256 = "bd7e326920fb5f89ad82c6932db2606ce32d26cf8492165115af57121cf41886"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+1/libgeotiff.v1.6.0.i686-w64-mingw32.tar.gz"
[[libgeotiff]]
arch = "powerpc64le"
git-tree-sha1 = "4543a5693382dd654ce10ffe88728a97277066f5"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "43f0f9127ea1e4d184503ea318b4f3abf9f9c4d8adb1a467d27d2862a9bea96e"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+1/libgeotiff.v1.6.0.powerpc64le-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "f883ad63ffbda1d2eb7db6aa701147aec784824f"
os = "macos"

    [[libgeotiff.download]]
    sha256 = "9ce101c15cfcd874cd526ed88273b53444508956554e4be5b61273dc946a1474"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+1/libgeotiff.v1.6.0.x86_64-apple-darwin.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "9ca33455ce20804c0b8e958415091ade12f534e1"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "0e9289aa00822c6e71e1392dda55db765b1b248ffbb1dbd2ec89b006818d79ae"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+1/libgeotiff.v1.6.0.x86_64-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "8ab711f37b54d9e067028d6dd78737696fcb717f"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "7060d5158700312df60fcf97f0bb7d42fd17316b909c80f842b926ce7d58f9f8"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+1/libgeotiff.v1.6.0.x86_64-linux-musl.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "480382c2fcc6c3f86737e10514b844efd7271d6c"
os = "freebsd"

    [[libgeotiff.download]]
    sha256 = "c85d33c243574b49bf00e1202648ea989c1209c537cb29aac3d394306be85565"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+1/libgeotiff.v1.6.0.x86_64-unknown-freebsd.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "3f1b12feb59c5ba75346ce47d9ccc46a614c1ca4"
os = "windows"

    [[libgeotiff.download]]
    sha256 = "555dba747b6849d6f2cfc9090e6c2b8b67e663d1301100db8d7802e3526aefc4"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v1.6.0+1/libgeotiff.v1.6.0.x86_64-w64-mingw32.tar.gz"
