[[libgeotiff]]
arch = "aarch64"
git-tree-sha1 = "d8b8ab4432262c09a95b48d10e4398e049530171"
os = "macos"

    [[libgeotiff.download]]
    sha256 = "982271aae7befd3527d1ca4c2fef2e0641d1ea71e1bca08e921656c1b6e10284"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.300+0/libgeotiff.v100.702.300.aarch64-apple-darwin.tar.gz"
[[libgeotiff]]
arch = "aarch64"
git-tree-sha1 = "95d50c4b631dc2f38e40f6c0382228ebd7d0be04"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "b28035d08b396f5d836e25cd9086e6634674829e271995fc3637ce925e32d655"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.300+0/libgeotiff.v100.702.300.aarch64-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "aarch64"
git-tree-sha1 = "b876dc546f620f77e097de03fdcfcc57f6c81dee"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "8aae8c0c27ffdb1e42c1778f3b468eb41229efc2248314b7cda7e7df9ed9d814"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.300+0/libgeotiff.v100.702.300.aarch64-linux-musl.tar.gz"
[[libgeotiff]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1fee05a4458fe122a045a6b197dc093ffbb228a4"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "45f4ff74ad048dca707f01137f68d569c93c749fa4a58e5a43bb90cd8b453d14"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.300+0/libgeotiff.v100.702.300.armv6l-linux-gnueabihf.tar.gz"
[[libgeotiff]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7afc86ac9f1a793a494f50144e651b851a3a02f0"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "c51f4a8b9fa88f907d3d5c1fd4189c1a71f4ed4fc908e7a22ff888aadce04869"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.300+0/libgeotiff.v100.702.300.armv6l-linux-musleabihf.tar.gz"
[[libgeotiff]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "027b41d058302456d05e81bfa94097f9277509e6"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "95b01b449641fe632f21867e9d8339ada67ed840e76b45d13cefaa1d882fbebc"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.300+0/libgeotiff.v100.702.300.armv7l-linux-gnueabihf.tar.gz"
[[libgeotiff]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e6e95bde78eb455d901cef2a132fef60e110082b"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "32b0b2bb41de77fda14ddc2ed2a8e51eac954a830d67e5b127c697dbb6969d7d"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.300+0/libgeotiff.v100.702.300.armv7l-linux-musleabihf.tar.gz"
[[libgeotiff]]
arch = "i686"
git-tree-sha1 = "1ed4d46ce7d374b70e66b6a881470ef7a6b35f26"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "0aa4bf1ffb2731c5fa362f7192a39f10a84e71680dab45f1a6e253451e5cf1c4"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.300+0/libgeotiff.v100.702.300.i686-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "i686"
git-tree-sha1 = "2c3b00e20222a085c8b08f3c19654e336353c3a2"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "b7d4ed0f562836b6b8692b3a3f7d279c0aa90833856afe86ad6c3ae723cb87ce"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.300+0/libgeotiff.v100.702.300.i686-linux-musl.tar.gz"
[[libgeotiff]]
arch = "i686"
git-tree-sha1 = "0c85367dfdb2798b3d3c9b239f638892e4443dba"
os = "windows"

    [[libgeotiff.download]]
    sha256 = "e053e08170a6b92e6256ca7a740fe48bef2fbb64fa2c3bcfe8bd31b3d1653e39"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.300+0/libgeotiff.v100.702.300.i686-w64-mingw32.tar.gz"
[[libgeotiff]]
arch = "powerpc64le"
git-tree-sha1 = "8b1395ae8c093eb745f3c72a7446892cb74ae341"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "b660e930842a8f4e4cb86652f47e1991be2f80f7d8a5004ebdbf6d9fa980b563"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.300+0/libgeotiff.v100.702.300.powerpc64le-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "89f54754c5c55aa72c1f68f07239c166e9cb7cee"
os = "macos"

    [[libgeotiff.download]]
    sha256 = "88a23430425257305225765ca9d3504856e274dd115872421a85f3103b463e62"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.300+0/libgeotiff.v100.702.300.x86_64-apple-darwin.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "9b0263aa6e3b32710cb995b9553a38daecf28296"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "633717e6ae7658f33307d2f60931816eb0ecbd35826160a123fb1fde08722921"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.300+0/libgeotiff.v100.702.300.x86_64-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "0069b6a09f671ce3d81ccfa8e1e5fdd7d7adbc44"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "a8cbc30756a26a74d449be77d0b05c710895167d6b879e6aec23fa9bf0251a59"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.300+0/libgeotiff.v100.702.300.x86_64-linux-musl.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "3f4d4b3fee1ce830c1835c2050284a67336c9e00"
os = "freebsd"

    [[libgeotiff.download]]
    sha256 = "c4266aec822b6fd6c53172d6a1bf6478a00618bdafc8176a70e0d8634fb85e5d"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.300+0/libgeotiff.v100.702.300.x86_64-unknown-freebsd.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "2c7cc55604206ad26f84e1945e87d59813aee2f4"
os = "windows"

    [[libgeotiff.download]]
    sha256 = "3a915c8cd12360664d8619a0fa89642fe8636d3d8895c80b4b0ad68dc63436cf"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.300+0/libgeotiff.v100.702.300.x86_64-w64-mingw32.tar.gz"
