[[libgeotiff]]
arch = "aarch64"
git-tree-sha1 = "99a3cc4fca09bb791c8b76c40daa9abee5fff3b3"
os = "macos"

    [[libgeotiff.download]]
    sha256 = "bb3c32d33cd802daeb61dcba5c8e54644ec24ad3cfddf10c4c72f65e256820bf"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.400+0/libgeotiff.v100.702.400.aarch64-apple-darwin.tar.gz"
[[libgeotiff]]
arch = "aarch64"
git-tree-sha1 = "403b09a53153e5f502b1e7b0c7a3a42127150cfa"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "993079aaac75a0a85027d5eb1a9109d5ae2b8a26561501c5ab34ff14b9790f2f"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.400+0/libgeotiff.v100.702.400.aarch64-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "aarch64"
git-tree-sha1 = "0b1668fe5166f5374ea5af819a1b5b52425fc7e7"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "9f76af59ec456b60f247ae306fc483181c75fdbd9acfbf5ca2a22555881ed163"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.400+0/libgeotiff.v100.702.400.aarch64-linux-musl.tar.gz"
[[libgeotiff]]
arch = "aarch64"
git-tree-sha1 = "b93ca2678ddb3ce43394d35f803178a1f0968e75"
os = "freebsd"

    [[libgeotiff.download]]
    sha256 = "b2ebc108aae7188be9c0eb703bf671c33e78e8a0f11ec3c8c8bba9044ee279c6"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.400+0/libgeotiff.v100.702.400.aarch64-unknown-freebsd.tar.gz"
[[libgeotiff]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a158eceaa3498387be38bdce504407fe58b6fab1"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "bd00dd072727e8338188666adf925d77bd12c174f603c15928b41a92ebcd36e9"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.400+0/libgeotiff.v100.702.400.armv6l-linux-gnueabihf.tar.gz"
[[libgeotiff]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e8be8f1d6a6aabc1039718924aac2b30544fa9e1"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "2f4564947ee97c2b8348edd306f562ffa33a50cd0e73d2f66c71288c7bef94d5"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.400+0/libgeotiff.v100.702.400.armv6l-linux-musleabihf.tar.gz"
[[libgeotiff]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "50a1c00ed30712efde66ec425dad617fb1906c69"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "f1322fd153dc0b87fe3c5ac09cfcb6f199d0658a76bc4019e8bacf95d9eeb3d2"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.400+0/libgeotiff.v100.702.400.armv7l-linux-gnueabihf.tar.gz"
[[libgeotiff]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "78f67afa812589b314ca968aaeada9585aa5c2d3"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "dcb26b94b6b24ac262c7e22fd12c3d5f95ebfc18775dc68ea29f3c1c38f0c52e"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.400+0/libgeotiff.v100.702.400.armv7l-linux-musleabihf.tar.gz"
[[libgeotiff]]
arch = "i686"
git-tree-sha1 = "2a61232ca36cfd2e6f67f44959d565a2cb2aad02"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "3a06bfd420db8b5ed62af9003ccc4dc0ba5d444459bd1ef09907f49fb9205b17"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.400+0/libgeotiff.v100.702.400.i686-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "i686"
git-tree-sha1 = "dc034a886c2d08e5c635a9be0fb223839312c784"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "82e8fcc19a184cb7381666d0f8b2bb7f173eacf6bad2b0d58173c81c3618f6cf"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.400+0/libgeotiff.v100.702.400.i686-linux-musl.tar.gz"
[[libgeotiff]]
arch = "i686"
git-tree-sha1 = "9b9876de85fb62c5a366a055dfdc583960d78a00"
os = "windows"

    [[libgeotiff.download]]
    sha256 = "da612bd2cdca417e9ddceee1054667cafecb47f7efd8bfe179784a588c9874b2"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.400+0/libgeotiff.v100.702.400.i686-w64-mingw32.tar.gz"
[[libgeotiff]]
arch = "powerpc64le"
git-tree-sha1 = "c22afe90ed3d60d3d926041339e43602430e1bb4"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "5cd95ea0f82591812d0ce7e2b2f84d669d215b1c66cc511dd87aa7450255153d"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.400+0/libgeotiff.v100.702.400.powerpc64le-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "riscv64"
git-tree-sha1 = "350f1f8c14a9bc7532a1d4f15866f2cfbeb384f4"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "e60ebacd0591ce4fcb09bf634b5221ed2ff7713f9cc957c73f9957c4a7ec9bc3"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.400+0/libgeotiff.v100.702.400.riscv64-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "92d553331d3ba7d4a5c9f9744a650951095f808e"
os = "macos"

    [[libgeotiff.download]]
    sha256 = "c27a8021fc3b7e7f3177acfaa00a9e4ab723740aeb15a8494617cf84338274ab"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.400+0/libgeotiff.v100.702.400.x86_64-apple-darwin.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "7967f0f1d4ed07fef48d8dfb3152d4a7ed703278"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "f51ff3496cd2b8183ff3e8ba74aa808cb71714640f08e7c657c7c165d18a7b1b"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.400+0/libgeotiff.v100.702.400.x86_64-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "531eaaec9d360a092e2e546c1ac35b164eac771a"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "ef17a966ced13cec8ae972f4bb6e8e98890c97ba6d61b1423184d3dce2a3c788"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.400+0/libgeotiff.v100.702.400.x86_64-linux-musl.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "a801deedebc0a4b1339d754dace0f0515c401b38"
os = "freebsd"

    [[libgeotiff.download]]
    sha256 = "6626d3eadcd688eada07d8006586ba83951f1c6e0118a1003629833850473447"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.400+0/libgeotiff.v100.702.400.x86_64-unknown-freebsd.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "7e390065eac61e880d9ed0f902a98e85dc913844"
os = "windows"

    [[libgeotiff.download]]
    sha256 = "58cb8b7cbe5dc238c239e6507ab9c573f794d6d750c1828eecb1b2470892f75a"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.702.400+0/libgeotiff.v100.702.400.x86_64-w64-mingw32.tar.gz"
