[[libgeotiff]]
arch = "aarch64"
git-tree-sha1 = "9cd88b624c5c9ad34fec9c61621c56d465a8c717"
os = "macos"

    [[libgeotiff.download]]
    sha256 = "453dab9472c45b92d3f90242855555b06cb66f312360c06d62ac2751272fdcd9"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.100+0/libgeotiff.v100.700.100.aarch64-apple-darwin.tar.gz"
[[libgeotiff]]
arch = "aarch64"
git-tree-sha1 = "dc19f16c09e34725af48e15612706b4d032fb57a"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "1df2576499a0e04c2474a361cd5b4af550c99fcad67ca6c22f8614467e2c98ee"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.100+0/libgeotiff.v100.700.100.aarch64-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "aarch64"
git-tree-sha1 = "d599679c6c7cddc4b15f79ebae4bee407f11a6d5"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "ba028c87f74250e59952e81a22b550738774fdfb0819c73c93daf9d7aef9153d"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.100+0/libgeotiff.v100.700.100.aarch64-linux-musl.tar.gz"
[[libgeotiff]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "333a7049cb0348a0ff1d0ce83c418a2b9c685186"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "180fdc8351d5dccbfc16305ed11c80a4753b50c820810f0837fb5f04666f5b75"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.100+0/libgeotiff.v100.700.100.armv6l-linux-gnueabihf.tar.gz"
[[libgeotiff]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1f42d4e5caa16cc33627b5196d137d0a306c92d0"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "e8e59d089b1ca7aa1dc5a9e68e67bfbed54c804a292904f98e6f8fd1985099b0"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.100+0/libgeotiff.v100.700.100.armv6l-linux-musleabihf.tar.gz"
[[libgeotiff]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1651ceb37035d0d58836f4ccb1badc3fd71e2be3"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "fc04db07395a5ab8947a2a545c55422128ef09dec580f380573ea1a9852274ab"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.100+0/libgeotiff.v100.700.100.armv7l-linux-gnueabihf.tar.gz"
[[libgeotiff]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9ba4957c12618207fe199a3b2cb78f20061fc521"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "71ae9900cb2d6e25ab10bc8e1052bf2dde60816e3e9e3de78e8009bf07583f91"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.100+0/libgeotiff.v100.700.100.armv7l-linux-musleabihf.tar.gz"
[[libgeotiff]]
arch = "i686"
git-tree-sha1 = "dd25f68f0bdca99fa5e207eb38d2495cf003faf2"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "c1b465cfdc3e8d67f1a81f071f9756fdeaf499d3af2e13ee91d6c7345a1a2199"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.100+0/libgeotiff.v100.700.100.i686-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "i686"
git-tree-sha1 = "bf38fb228a65147d9aeb1aa878175a6f6ed40010"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "881cc00cf145b6a6da714abe1948cf73e5c8e42192b335f8dfff6a414369a700"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.100+0/libgeotiff.v100.700.100.i686-linux-musl.tar.gz"
[[libgeotiff]]
arch = "i686"
git-tree-sha1 = "8ce033f05632b82e6017773b02b3365aa455b01b"
os = "windows"

    [[libgeotiff.download]]
    sha256 = "46dd35aa3985f1e2753eb7cbafdd320ca0eb5651f3a04b845a7fdd120cb92c8f"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.100+0/libgeotiff.v100.700.100.i686-w64-mingw32.tar.gz"
[[libgeotiff]]
arch = "powerpc64le"
git-tree-sha1 = "f623372a1a5e916fdf859cb1c5c8275fb0e2cc29"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "8df2ee6d121642f260daa5dbd37a3e17994b728cb9f7cba348d93e31b176e641"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.100+0/libgeotiff.v100.700.100.powerpc64le-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "8ce24195010de79b457ba6126cb11f63132de043"
os = "macos"

    [[libgeotiff.download]]
    sha256 = "cfdf9dbba447710a9d48c1ddb30061ef5ff351651408f2d2924584801a0ba6ac"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.100+0/libgeotiff.v100.700.100.x86_64-apple-darwin.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "e4afa6442d82c9e3819067808b91aa8308d90db6"
libc = "glibc"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "8c49923a25cb0187dd232d43ce7818401c4dd5e09d19c4b3d514187e7a407ded"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.100+0/libgeotiff.v100.700.100.x86_64-linux-gnu.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "b0b9a6a9a0e46b81e3d546936a8aef39fab19d01"
libc = "musl"
os = "linux"

    [[libgeotiff.download]]
    sha256 = "f9367cd0fcc633fe081942d770dca44e2741a27b66b14a3caed27466e0414fd1"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.100+0/libgeotiff.v100.700.100.x86_64-linux-musl.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "45fef013acde447061b4d0ec00e690d12d7b4a09"
os = "freebsd"

    [[libgeotiff.download]]
    sha256 = "0a6a02348563760349f892278d8ba7cb66b23aa88fdeafc6c0b2119aec18c11a"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.100+0/libgeotiff.v100.700.100.x86_64-unknown-freebsd.tar.gz"
[[libgeotiff]]
arch = "x86_64"
git-tree-sha1 = "18a38c3afb63ea0df1832d3f946b21b58ba401ea"
os = "windows"

    [[libgeotiff.download]]
    sha256 = "ab6cfdd6218dc503e72a94d2781f028acc217b3c65a553e3e6d5cc1cdf9c8d8f"
    url = "https://github.com/JuliaBinaryWrappers/libgeotiff_jll.jl/releases/download/libgeotiff-v100.700.100+0/libgeotiff.v100.700.100.x86_64-w64-mingw32.tar.gz"
